trigger:
  - sampleCode
pool:
  vmImage: ubuntu-latest
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.13'
    displayName: 'Setup Python'

  - script: |
      cd samples/javascript/playwright
      npm install
      npx playwright install-deps
      npx playwright install
      npx playwright test
    displayName: 'Run Playwright tests'
    continueOnError: true

  - script: |
      cd samples/javascript/playwright
      pip install trcli
      trcli -y \
        -h "https://INSTANCE-NAME.testrail.io" \
        --project "AzurePipelinesExamples" \
        -u "USERNAME" \
        -p "PASSWORD" \
        parse_junit \
        -f "test-results/junit-report.xml" \
        --title "Playwright automated tests" \
        --run-description "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
    displayName: 'Upload Playwright Test Results in TestRail with TestRail CLI'